### ISSUE TITLE
Open terminal in a python virtualenv

### ISSUE THREAD

**Issue by jgarte** [davidshepherd7/terminal-here#34]
Hi, has anyone tried opening a terminal in a python virtualenv?

My use case is that I would like to do something like the following:

```
(defcustom multiple-cursors-terminal "kitty"
  "The terminal to launch pudb in."
  :type 'string)

(defun pudb ()
  "Launch pudb from emacs"
  (interactive)
  (if (executable-find "pudb3")
      (shell-command (concat multiple-cursors-terminal
                             " -e pudb3 "
                             (buffer-file-name (current-buffer))))
      (user-error "pudb3 is not found in PATH")))
```

Do you recommend using anything from `terminal-here` as a library for my use case here?

**Comment by jgarte** [comment]
I refactored the above to use `terminal-here`:

```
(require 'terminal-here)
(setq terminal-here-linux-terminal-command 'kitty)

(defun vis ()
  "Launches vis on the current buffer, line, and column."
  (interactive)
  (if (executable-find "vis")
      (shell-command (concat (symbol-name terminal-here-linux-terminal-command)
                             " -e vis +"
                             (number-to-string (line-number-at-pos))
                             "x/./g" 
                             (number-to-string (current-column))
                             " "
                             (buffer-file-name (current-buffer))))
      (user-error "vis is not found in PATH")))

;; use if-let here to find executable?
(defun pudb ()
  "Launches pudb on the current buffer."
  (interactive)
  (if (executable-find "pudb3")
      (shell-command (concat (symbol-name terminal-here-linux-terminal-command)
                             " -e pudb3 "
                             (buffer-file-name (current-buffer))))
      (user-error "pudb is not found in PATH")))
```

Would it be possible for `terminal-here` to support launching arbitrary programs like [pudb](https://documen.tician.de/pudb/starting.html) or [vis](https://github.com/martanne/vis) in a terminal?

**Comment by davidshepherd7** [comment]
Yeah this seems like an interested and useful feature to have, I might figure out how to implement nice support for it when I have some free time.

For now what you have there should work fine for most terminals on Linux, but:

1. `(symbol-name terminal-here-linux-terminal-command)` is not necessarily a string that you can used to run the command (e.g. look [here](https://github.com/davidshepherd7/terminal-here/blob/dev/terminal-here.el#L211) at suckless term on Linux, iTerm.app on Mac or cmd on Windows). This might bite you if you change terminal or platform?
2. Similarly `"-e"` isn't necessarily the right flag for all terminals, see [here](https://github.com/davidshepherd7/terminal-here/blob/dev/terminal-here.el#L246).

I think the code to handle all this properly would be something like:

```
(defun run-my-command (dir)
    (terminal-here--run-command 
        (append 
            (terminal-here--term-command dir) 
            (list 
                (terminal-here--get-command-flag) 
                "your" "command" "here" (buffer-file-name (current-buffer)))))
```

Note that here you need a list of strings for the arguments to the shell command, but your version uses a single string with space separated arguments (terminal-here uses `start-process` rather than `shell-command` because it's more secure/less prone to weirdness if the arguments contain shell control characters).

**Comment by davidshepherd7** [comment]
I've added support for this in master, try it out!

Documentation is here: https://github.com/davidshepherd7/terminal-here#inner-commands

**Comment by jgarte** [comment]
@davidshepherd7 Woahh just saw this now. Happy New Year! I'll try this week and report back after I use it a bit. Thanks!
